const httpMessage = {
    "UNKNOWN": "Unknown",
    "SWITCHING_PROTOCOLS": "Switching protocols",
    "OK": "Ok",
    "CREATED": "Created",
    "ACCEPTED": "Accepted",
    "NON_AUTHORITATIVE_INFORMATION": "Non authoritative information",
    "NO_CONTENT": "No content",
    "RESET_CONTENT": "Reset content",
    "PARTIAL_CONTENT": "Partial content",
    "MULTIPLE_CHOICES": "Multiple choices",
    "MOVED_PERMANENTLY": "Moved permanently",
    "MOVED_TEMPORARILY": "Moved temporarily",
    "SEE_OTHER": "See other",
    "NOT_MODIFIED": "Not modified",
    "USE_PROXY": "Use proxy",
    "BAD_REQUEST": "Bad request",
    "UNAUTHORIZED": "Unauthorized",
    "PAYMENT_REQUIRED": "Payment required",
    "FORBIDDEN": "Forbidden",
    "NOT_FOUND": "Not found",
    "METHOD_NOT_ALLOWED": "Method not allowed",
    "NOT_ACCEPTABLE": "Not acceptable",
    "PROXY_AUTHENTICATION_REQUIRED": "Proxy authentication required",
    "REQUEST_TIMEOUT": "Request timeout",
    "CONFLICT": "Conflict",
    "GONE": "Gone",
    "LENGTH_REQUIRED": "Length required",
    "PRECONDITION_FAILED": "Precondition failed",
    "REQUEST_ENTITY_TOO_LARGE": "Request entity too large",
    "REQUEST_URI_TOO_LARGE": "Request uri too large",
    "UNSUPPORTED_MEDIA_TYPE": "Unsupported media type",
    "REQUESTED_RANGE_NOT_SATISFIABLE": "Requested range not satisfiable",
    "EXPECTATION_FAILED": "Expectation failed",
    "IM_A_TEAPOT": "Im a teapot",
    "INTERNAL_SERVER_ERROR": "Internal server error",
    "NOT_IMPLEMENTED": "Not implemented",
    "BAD_GATEWAY": "Bad gateway",
    "SERVICE_UNAVAILABLE": "Service unavailable",
    "GATEWAY_TIMEOUT": "Gateway timeout",
    "HTTP_VERSION_NOT_SUPPORTED": "Http version not supported"
}

export default httpMessage